package mx.eltec.oxxomonitor.adapters



class plantillaStruct {
    private val dataList = mutableListOf<Data>()

    init {
        initializeData()
    }
    data class Data(val campo: String, val largo: Int)
    data class Rango(val clave: String, val inicio: Int, val final: Int)
    private fun initializeData() {
        // Agregar los datos a la lista
        dataList.add(Data("Dato-de_seguridad_1", 2))
        dataList.add(Data("T0", 4))
        dataList.add(Data("T1", 4))
        dataList.add(Data("T2", 4))
        dataList.add(Data("T3", 4))
        dataList.add(Data("T4", 4))
        dataList.add(Data("T5", 4))
        dataList.add(Data("T6", 4))
        dataList.add(Data("T7", 4))
        dataList.add(Data("T8", 4))
        dataList.add(Data("T9", 4))
        dataList.add(Data("TA", 4))
        dataList.add(Data("TB", 4))
        dataList.add(Data("TC", 4))
        dataList.add(Data("TD", 4))
        dataList.add(Data("TE", 4))
        dataList.add(Data("TF", 4))
        dataList.add(Data("A0", 4))
        dataList.add(Data("A1", 4))
        dataList.add(Data("A2", 4))
        dataList.add(Data("A3", 4))
        dataList.add(Data("A4", 4))
        dataList.add(Data("A5", 4))
        dataList.add(Data("A6", 4))
        dataList.add(Data("A7", 4))
        dataList.add(Data("A8", 4))
        dataList.add(Data("A9", 4))
        dataList.add(Data("AA", 4))
        dataList.add(Data("AB", 4))
        dataList.add(Data("AC", 4))
        dataList.add(Data("AD", 4))
        dataList.add(Data("AE", 4))
        dataList.add(Data("AF", 4))
        dataList.add(Data("Dato-de_seguridad_2", 2))
        dataList.add(Data("L0", 2))
        dataList.add(Data("L1", 2))
        dataList.add(Data("L2", 2))
        dataList.add(Data("L3", 2))
        dataList.add(Data("L4", 2))
        dataList.add(Data("L5", 2))
        dataList.add(Data("L6", 2))
        dataList.add(Data("L7", 2))
        dataList.add(Data("L8", 2))
        dataList.add(Data("L9", 2))
        dataList.add(Data("LA", 2))
        dataList.add(Data("LB", 2))
        dataList.add(Data("LC", 2))
        dataList.add(Data("LD", 2))
        dataList.add(Data("LE", 2))
        dataList.add(Data("LF", 2))
        dataList.add(Data("C0", 2))
        dataList.add(Data("C1", 2))
        dataList.add(Data("C2", 2))
        dataList.add(Data("C3", 2))
        dataList.add(Data("C4", 2))
        dataList.add(Data("C5", 2))
        dataList.add(Data("C6", 2))
        dataList.add(Data("C7", 2))
        dataList.add(Data("C8", 2))
        dataList.add(Data("C9", 2))
        dataList.add(Data("CA", 2))
        dataList.add(Data("CB", 2))
        dataList.add(Data("CC", 2))
        dataList.add(Data("CD", 2))
        dataList.add(Data("CE", 2))
        dataList.add(Data("CF", 2))
        dataList.add(Data("F0", 2))
        dataList.add(Data("F1", 2))
        dataList.add(Data("F2", 2))
        dataList.add(Data("F3", 2))
        dataList.add(Data("F4", 2))
        dataList.add(Data("F5", 2))
        dataList.add(Data("F6", 2))
        dataList.add(Data("F7", 2))
        dataList.add(Data("F8", 2))
        dataList.add(Data("F9", 2))
        dataList.add(Data("FA", 2))
        dataList.add(Data("FB", 2))
        dataList.add(Data("FC", 2))
        dataList.add(Data("FD", 2))
        dataList.add(Data("FE", 2))
        dataList.add(Data("FF", 2))
        dataList.add(Data("D0", 2))
        dataList.add(Data("D1", 2))
        dataList.add(Data("D2", 2))
        dataList.add(Data("D3", 2))
        dataList.add(Data("D4", 2))
        dataList.add(Data("D5", 2))
        dataList.add(Data("D6", 2))
        dataList.add(Data("D7", 2))
        dataList.add(Data("E0", 2))
        dataList.add(Data("E1", 2))
        dataList.add(Data("E2", 2))
        dataList.add(Data("E3", 4))
        dataList.add(Data("Dato-de_seguridad_3", 2))
    }

    fun getDataList(): List<Data> {
        return dataList
    }
    companion object {

    }
}